Mark the dirty checks as type: ignore
I'm not quite sure why this is needed, but mypy gives us:

    ratbag/drivers/example_driver.py:93: error: Function "Callable[..., Any]" could always be true in boolean context  [truthy-function]

I'm assuming this is because the @Gobject.property decorator is detected
as function, not as property. So while this works at runtime it's not
obvious to mypy.