test: fill in the mock object
New versions of dbus_next do signature verification, so our backing
mock object needs to have valid value for each of the properties ratbagd
exports over dbus. Otherwise we get a lot of errors in the form:

   dbus_next.errors.SignatureBodyMismatchError: DBus BOOLEAN type "b" must be Python type "bool", got <class 'unittest.mock.MagicMock'>